global:
  resolve_timeout: 1m
  slack_api_url: 'https://hooks.slack.com/services/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'

route:
  receiver: 'slack-notifications'

receivers:
- name: 'slack-notifications'
  slack_configs:
  - channel: '#monitoring-instances'
    send_resolved: true